### ISSUE TITLE
Getting error on gradle build: Could not find method bootJar

### ISSUE THREAD

**Issue by coderkd10** [spring-guides/gs-gradle#23]
When I run `gradle build` (or even `gradle tasks` / `./gradlew build`) I get the error -

```
> Could not find method bootJar() for arguments ...
```

I noticed that a recent commit 015dbc1 replaced `jar` with `bootJar`, I don't understand why? I also noticed that [CI server also shows the same error](https://travis-ci.org/spring-guides/gs-gradle/builds/395169912?utm_source=github_status&utm_medium=notification). Was this a typo?

**Comment by gregturn** [comment]
This is the one guide that does NOT use the Boot plugin, so upgrading to bootJar task was incorrect.

Resolved via https://github.com/spring-guides/gs-gradle/commit/5cec2afceb4c85d11b1a73ce08ef9917e36d8bb8
