### ISSUE TITLE
This tutorial is out of date

### ISSUE THREAD

**Issue by donhuvy** [spring-guides/gs-gradle#24]
It should use Gradle 4.8.1 , JDK 10, and Joda time is no need since Java 8 Date time API

**Comment by kktn-FW** [comment]
In my environment, "./gradlew" doesn't work with "$ gradle wrapper --gradle-version 2.13" because it might be too old version. I think it is better to update the document for beginners like me.

**Comment by Exadra37** [comment]
Well it seems that this repo is dead... 

Issues and Pull requests are being ignored :(

**Comment by crashspringfield** [comment]
and the build only works if `build.gradle` specifies:

    mainClassName = 'main.java.hello.HelloWorld'

**Comment by snicoll** [comment]
Sorry everyone for the delay. This is superseded by #29 that got merged.
